### ISSUE TITLE
Can it detect when a premake is needed in the background?

### ISSUE THREAD

**Issue by ubershmekel** [tvandijck/PremakeExtension#1]
I'm guessing it would have to run the premake and diff to find out.

**Comment by tvandijck** [comment]
Yeah, it would basically have to run premake with every file add/remove or lua file modification.. Technically possible, but I really don't want to occupy a CPU 100% for all of eternity to do that.

**Comment by ubershmekel** [comment]
I guess it could poll for SVN/Git revision before it checks. But that may be out of scope.
